/* ═══════════════════════════════════════════════════════════════════
   DATA — All GOT content
   ═══════════════════════════════════════════════════════════════════ */

export const KINGDOMS = [
  {
    id: 'north',
    region: 'THE NORTH',
    place: 'WINTERFELL',
    kingdom: 'Kingdom of the North',
    desc: 'The ancient capital of the Kings of Winter. winterfell is a massive stone fortress constructed by Bran the Builder, standing resilient against the freezing winds and the horrors of the wild beyond the Neck.',
    img: '/images/kingdoms/north.png',
    accent: '#8fafc4',
    bg: '#0d1117',
    ctaLabel: 'Explore Winterfell',
    ctaHref: '/houses.html#stark',
    bgNum: '01',
    sigil: '❄️'
  },
  {
    id: 'vale',
    region: 'THE VALE OF ARRYN',
    place: 'THE EYRIE',
    kingdom: 'Kingdom of the Mountain and the Vale',
    desc: 'Perched high atop the Giant\'s Lance mountain, the Eyrie is an impregnable castle of white stone. It was the ancestral seat of the Kings of the Mountain and Vale, unreachable by hostile armies.',
    img: '/images/kingdoms/vale_real.jpg',
    accent: '#6a8ab0',
    bg: '#080d14',
    ctaLabel: 'Explore The Eyrie',
    ctaHref: '/houses.html#arryn',
    bgNum: '02',
    sigil: '🦅'
  },
  {
    id: 'rivers',
    region: 'THE RIVERS & ISLES',
    place: 'HARRENHAL',
    kingdom: 'Kingdom of the Isles and the Rivers',
    desc: 'The colossal, melted black ruins of Harrenhal stand as a dark monument to the arrogance of Harren the Black. Built to be the largest castle in Westeros, it was consumed by dragon fire.',
    img: '/images/kingdoms/harrenhal_real.jpg',
    accent: '#b8a040',
    bg: '#050810',
    ctaLabel: 'Explore Harrenhal',
    ctaHref: '/houses.html#greyjoy',
    bgNum: '03',
    sigil: '🏰'
  },
  {
    id: 'rock',
    region: 'THE WESTERLANDS',
    place: 'CASTERLY ROCK',
    kingdom: 'Kingdom of the Rock',
    desc: 'A colossal fortress carved out of a massive stone mount overlooking the Sunset Sea. It was the golden seat of the Kings of the Rock, fueled by the rich gold mines within the hills.',
    img: '/images/kingdoms/casterly_rock_real.jpg',
    accent: '#d4a84b',
    bg: '#1a1200',
    ctaLabel: 'Explore Casterly Rock',
    ctaHref: '/houses.html#lannister',
    bgNum: '04',
    sigil: '🦁'
  },
  {
    id: 'reach',
    region: 'THE REACH',
    place: 'HIGHGARDEN',
    kingdom: 'Kingdom of the Reach',
    desc: 'The cultural center and breadbasket of Westeros. Highgarden is a beautiful castle surrounded by white stone walls, lush gardens, and golden roses, once ruled by the legendary Gardener Kings.',
    img: '/images/kingdoms/highgarden_real.jpg',
    accent: '#5a9e48',
    bg: '#030a00',
    ctaLabel: 'Explore Highgarden',
    ctaHref: '/houses.html#tyrell',
    bgNum: '05',
    sigil: '🌹'
  },
  {
    id: 'stormlands',
    region: 'THE STORMLANDS',
    place: 'STORM\'S END',
    kingdom: 'The Stormlands',
    desc: 'A legendary castle built to withstand the wrath of the sea god and wind god. Surrounded by massive circular stone walls, it was the formidable seat of the ancient Storm Kings.',
    img: '/images/kingdoms/storm_send_real.jpg',
    accent: '#c9a84c',
    bg: '#0a0a00',
    ctaLabel: 'Explore Storm\'s End',
    ctaHref: '/houses.html#baratheon',
    bgNum: '06',
    sigil: '⚡'
  },
  {
    id: 'dorne',
    region: 'DORNE',
    place: 'SUNSPEAR',
    kingdom: 'Dorne',
    desc: 'A desert stronghold of mud-brick towers, domes, and gilded spires. Sunspear is the capital of Dorne, the only kingdom that successfully resisted Aegon\'s Conquest through clever desert warfare.',
    img: '/images/kingdoms/sunspear_dorne_real.jpg',
    accent: '#e07020',
    bg: '#1a0800',
    ctaLabel: 'Explore Sunspear',
    ctaHref: '/houses.html#martell',
    bgNum: '07',
    sigil: '☀️'
  }
];
export const HOUSES = [
  { id:'stark',     name:'STARK',     seat:'Winterfell',     words:'"Winter Is Coming"',     region:'The North',       sigil:'Grey Direwolf',         accent:'#8fafc4', border:'#4a6380', glow:'rgba(143,175,196,0.08)', img:'/images/houses/stark.svg',   bg:'linear-gradient(135deg, #0d1117 0%, #1a2332 60%, #0d1117 100%)', description:'Wardens of the North, the Starks trace their blood to the First Men. Honour is their sword and the frozen wind their banner. They endure where others fall — patient as winter itself.' },
  { id:'lannister', name:'LANNISTER', seat:'Casterly Rock',  words:'"Hear Me Roar"',         region:'The Westerlands', sigil:'Golden Lion',            accent:'#d4a84b', border:'#7a6130', glow:'rgba(212,168,75,0.08)', img:'/images/houses/lannister.svg',   bg:'linear-gradient(135deg, #1a1200 0%, #2a1f00 60%, #1a1200 100%)', description:'The wealthiest house in Westeros. Their lion does not merely roar — it devours. Power is their birthright, gold their language, and debt a weapon they wield with surgical precision.' },
  { id:'targaryen', name:'TARGARYEN', seat:'Dragonstone',    words:'"Fire and Blood"',       region:'The Crownlands', sigil:'Three-Headed Dragon',    accent:'#c0392b', border:'#7a1a1a', glow:'rgba(192,57,43,0.08)', img:'/images/houses/targaryen.svg', bg:'linear-gradient(135deg, #1a0000 0%, #2d0a0a 60%, #1a0000 100%)', description:'Blood of Old Valyria. They did not conquer Westeros — they burned it into submission. Dragon riders, dynasty builders, and the last of a world consumed by fire.' },
  { id:'baratheon', name:'BARATHEON', seat:"Storm's End",    words:'"Ours Is The Fury"',     region:'The Stormlands', sigil:'Crowned Black Stag',     accent:'#c9a84c', border:'#5a5020', glow:'rgba(201,168,76,0.08)', img:'/images/houses/baratheon.svg', bg:'linear-gradient(135deg, #0a0a00 0%, #1f1c00 60%, #0a0a00 100%)', description:'Born of storms, tempered by battle. The Baratheons seized the Iron Throne not through cunning but through iron will and a war hammer. Fury is not their weakness — it is their crown.' },
  { id:'greyjoy',   name:'GREYJOY',   seat:'Pyke',           words:'"We Do Not Sow"',        region:'The Iron Islands', sigil:'Golden Kraken',        accent:'#b8a040', border:'#3a4a5a', glow:'rgba(184,160,64,0.08)', img:'/images/houses/greyjoy.svg',  bg:'linear-gradient(135deg, #050810 0%, #0a1020 60%, #050810 100%)', description:'Reavers of the sea. Iron men who bow to no king but the Drowned God. What they cannot make, they take. What they cannot take, they burn.' },
  { id:'tyrell',    name:'TYRELL',    seat:'Highgarden',     words:'"Growing Strong"',       region:'The Reach',       sigil:'Golden Rose',           accent:'#5a9e48', border:'#2a4a20', glow:'rgba(90,158,72,0.08)', img:'/images/houses/tyrell.svg',   bg:'linear-gradient(135deg, #030a00 0%, #0a1800 60%, #030a00 100%)', description:'The richest lords of the Reach, whose roses feed the realm. Behind beauty lies ruthless ambition — growing strong in gardens, and stronger still in schemes.' },
  { id:'martell',   name:'MARTELL',   seat:'Sunspear',       words:'"Unbowed, Unbent, Unbroken"', region:'Dorne',     sigil:'Sun & Spear',           accent:'#e07020', border:'#7a3a10', glow:'rgba(224,112,32,0.08)', img:'/images/houses/martell.svg', bg:'linear-gradient(135deg, #1a0800 0%, #2d1200 60%, #1a0800 100%)', description:'The unbowed lords of Dorne. While the rest of Westeros knelt to Aegon the Conqueror, the Martells danced through fire and emerged defiant.' },
  { id:'arryn',     name:'ARRYN',     seat:'The Eyrie',      words:'"As High As Honor"',     region:'The Vale',        sigil:'Moon-and-Falcon',       accent:'#6a8ab0', border:'#3a5070', glow:'rgba(106,138,176,0.08)', img:'/images/houses/arryn.svg', bg:'linear-gradient(135deg, #080d14 0%, #101a28 60%, #080d14 100%)', description:'High in their impregnable mountain fortress, the Arryns look down upon the realm. Their honor is their shield — their altitude, their advantage.' },
  { id:'tully',     name:'TULLY',     seat:'Riverrun',       words:'"Family, Duty, Honor"',  region:'The Riverlands',  sigil:'Silver Trout',          accent:'#4080a0', border:'#2a5068', glow:'rgba(64,128,160,0.08)', img:'/images/houses/tully.svg', bg:'linear-gradient(135deg, #060a10 0%, #0a1420 60%, #060a10 100%)', description:'Lords of the Riverlands, where every war passes through. The Tullys bind their bannermen with loyalty, not fear — family above all, duty to the end.' },
];
export const CHARACTERS = [
  { id:'jon-snow',        name:'Jon Snow',           house:'Stark / Targaryen', titles:['King in the North','Lord Commander of the Night\'s Watch','The White Wolf'], status:'alive',  accent:'#8fafc4', img:'/images/characters/jon-snow_clean.jpg' },
  { id:'daenerys',        name:'Daenerys Targaryen', house:'Targaryen',  titles:['Mother of Dragons','Breaker of Chains','Khaleesi of the Great Grass Sea'],        status:'dead',   accent:'#c0392b', img:'/images/characters/daenerys_clean.jpg' },
  { id:'tyrion',          name:'Tyrion Lannister',   house:'Lannister',  titles:['Hand of the King','Lord of Casterly Rock','The Imp'],                              status:'alive',  accent:'#d4a84b', img:'/images/characters/tyrion_clean.jpg' },
  { id:'cersei',          name:'Cersei Lannister',   house:'Lannister',  titles:['Queen of the Seven Kingdoms','Light of the West','Protector of the Realm'],         status:'dead',   accent:'#d4a84b', img:'/images/characters/cersei_clean.jpg' },
  { id:'arya-stark',      name:'Arya Stark',         house:'Stark',      titles:['No One','The Girl with No Name','Hero of Winterfell'],                              status:'alive',  accent:'#8fafc4', img:'/images/characters/arya-stark_clean.jpg' },
  { id:'sansa-stark',     name:'Sansa Stark',        house:'Stark',      titles:['Queen in the North','Lady of Winterfell'],                                          status:'alive',  accent:'#8fafc4', img:'/images/characters/sansa-stark_clean.jpg' },
  { id:'bran-stark',      name:'Bran Stark',         house:'Stark',      titles:['Bran the Broken','King of the Six Kingdoms','The Three-Eyed Raven'],                 status:'alive',  accent:'#8fafc4', img:'/images/characters/bran-stark_clean.jpg' },
  { id:'ned-stark',       name:'Eddard Stark',       house:'Stark',      titles:['Lord of Winterfell','Warden of the North','Hand of the King'],                       status:'dead',   accent:'#8fafc4', img:'/images/characters/ned-stark_clean.jpg' },
  { id:'jaime',           name:'Jaime Lannister',    house:'Lannister',  titles:['Kingslayer','Lord Commander of the Kingsguard','The Oathbreaker'],                   status:'dead',   accent:'#d4a84b', img:'/images/characters/jaime_clean.jpg' },
  { id:'joffrey',         name:'Joffrey Baratheon',  house:'Baratheon',  titles:['King of the Andals and the First Men'],                                              status:'dead',   accent:'#c9a84c', img:'/images/characters/joffrey_clean.jpg' },
  { id:'robb-stark',      name:'Robb Stark',         house:'Stark',      titles:['The Young Wolf','King in the North'],                                                status:'dead',   accent:'#8fafc4', img:'/images/characters/robb-stark_clean.jpg' },
  { id:'khal-drogo',      name:'Khal Drogo',         house:'Dothraki',   titles:['Khal of the Great Grass Sea','The Great Rider'],                                     status:'dead',   accent:'#8a6030', img:'/images/characters/khal-drogo_actor.jpg' },
  { id:'petyr-baelish',   name:'Petyr Baelish',      house:'None',       titles:['Littlefinger','Lord Protector of the Vale','Master of Coin'],                        status:'dead',   accent:'#5a5a5a', img:'/images/characters/petyr-baelish_actor.jpg' },
  { id:'varys',           name:'Varys',              house:'None',       titles:['The Spider','Master of Whisperers'],                                                 status:'dead',   accent:'#6a5a80', img:'/images/characters/varys_clean.jpg' },
  { id:'theon-greyjoy',   name:'Theon Greyjoy',      house:'Greyjoy',    titles:['Prince of the Iron Islands','Reek'],                                                 status:'dead',   accent:'#b8a040', img:'/images/characters/theon-greyjoy_clean.jpg' },
  { id:'brienne',         name:'Brienne of Tarth',   house:'Tarth',      titles:['Brienne the Beauty','Lord Commander of the Kingsguard'],                              status:'alive',  accent:'#4a6a90', img:'/images/characters/brienne_clean.jpg' },
  { id:'the-hound',       name:'Sandor Clegane',     house:'Clegane',    titles:['The Hound'],                                                                         status:'dead',   accent:'#5a4a3a', img:'/images/characters/the-hound_clean.jpg' },
  { id:'night-king',      name:'The Night King',     house:'White Walkers', titles:['Commander of the Army of the Dead','The Great Other'],                             status:'dead',   accent:'#3a6a8a', img:'/images/characters/night-king_actor.jpg' },
  { id:'margaery',        name:'Margaery Tyrell',    house:'Tyrell',     titles:['Queen of the Seven Kingdoms','The Little Rose'],                                      status:'dead',   accent:'#5a9e48', img:'/images/characters/margaery_clean.jpg' },
  { id:'samwell',         name:'Samwell Tarly',      house:'Tarly',      titles:['Slayer','Grand Maester'],                                                            status:'alive',  accent:'#5a6a50', img:'/images/characters/samwell_clean.jpg' },
  { id:'olenna',          name:'Olenna Tyrell',      house:'Tyrell',     titles:['The Queen of Thorns','Lady of Highgarden'],                                           status:'dead',   accent:'#5a9e48', img:'/images/characters/olenna_actor.jpg' },
  { id:'stannis',         name:'Stannis Baratheon',   house:'Baratheon', titles:['King of the Andals','The Mannis','Lord of Dragonstone'],                               status:'dead',   accent:'#c9a84c', img:'/images/characters/stannis_clean.jpg' },
  // ── HOUSE OF THE DRAGON CHARACTERS ──
  { id:'rhaenyra',        name:'Rhaenyra Targaryen',  house:'Targaryen', titles:['The Black Queen','Heir to the Iron Throne','Realm\'s Delight'],                        status:'dead',   accent:'#c0392b', img:'/images/characters/rhaenyra_actor.jpg' },
  { id:'daemon',          name:'Daemon Targaryen',    house:'Targaryen', titles:['The Rogue Prince','King Consort','Protector of the Realm'],                            status:'dead',   accent:'#b02a2a', img:'/images/characters/daemon_actor.jpg' },
  { id:'viserys-i',       name:'Viserys I Targaryen', house:'Targaryen', titles:['The Peaceful King','King of the Andals, the Rhoynar, and the First Men'],              status:'dead',   accent:'#c0392b', img:'/images/characters/viserys-i_actor.jpg' },
  { id:'alicent',         name:'Alicent Hightower',   house:'Hightower', titles:['The Green Queen','Queen Dowager'],                                                     status:'alive',  accent:'#5a9e48', img:'/images/characters/alicent_actor.jpg' },
  { id:'aegon-ii',        name:'Aegon II Targaryen',  house:'Targaryen', titles:['The Usurper','King of the Andals, the Rhoynar, and the First Men'],                    status:'alive',  accent:'#e5c276', img:'/images/characters/aegon-ii_actor.jpg' },
  { id:'aemond',          name:'Aemond Targaryen',    house:'Targaryen', titles:['Aemond One-Eye','Prince Regent'],                                                      status:'alive',  accent:'#4a6a50', img:'/images/characters/aemond_actor.jpg' },
  { id:'corlys',          name:'Corlys Velaryon',     house:'Velaryon',  titles:['The Sea Snake','Lord of the Tides','Master of Driftmark'],                             status:'alive',  accent:'#4080a0', img:'/images/characters/corlys_actor.jpg' },
  { id:'rhaenys',         name:'Rhaenys Targaryen',   house:'Targaryen', titles:['The Queen Who Never Was','Lady of Driftmark'],                                         status:'dead',   accent:'#c0392b', img:'/images/characters/rhaenys_actor.jpg' },
  { id:'criston',         name:'Criston Cole',        house:'Cole',      titles:['The Kingmaker','Lord Commander of the Kingsguard','Hand of the King'],                 status:'alive',  accent:'#b8a040', img:'/images/characters/criston_actor.jpg' },
  { id:'otto',            name:'Otto Hightower',      house:'Hightower', titles:['Hand of the King'],                                                                    status:'alive',  accent:'#5a9e48', img:'/images/characters/otto_actor.jpg' },
]
export const DRAGONS = [
  { id:'drogon',    name:'Drogon',    rider:'Daenerys Targaryen',     size:'The largest living dragon',                fire:'Black and red flames',   status:'alive',  accent:'#c41e3a', img:'/images/dragons/drogon.jpg',  description:'Named after Khal Drogo. The largest and most aggressive of Daenerys\'s three dragons. Black scales with red markings. His fire forged and destroyed cities.' },
  { id:'rhaegal',   name:'Rhaegal',   rider:'Jon Snow / Daenerys',    size:'Second largest of the three',             fire:'Orange-yellow flames',   status:'dead',   accent:'#4a7c3f', img:'/images/dragons/rhaegal.jpg', description:'Named after Rhaegar Targaryen. Green and bronze scales. Ridden briefly by Jon Snow before being shot down by Euron Greyjoy\'s scorpion bolts.' },
  { id:'viserion',  name:'Viserion',  rider:'The Night King (undead)', size:'Slightly smaller than Rhaegal',           fire:'Blue ice-fire (undead)', status:'dead',   accent:'#3a6a8a', img:'/images/dragons/viserion.jpg', description:'Named after Viserys Targaryen. Cream and gold scales. Killed by the Night King and resurrected as an ice dragon. Destroyed the Wall at Eastwatch.' },
  { id:'balerion',  name:'Balerion the Black Dread', rider:'Aegon the Conqueror', size:'Largest dragon in history', fire:'Black flame',            status:'dead',   accent:'#2a2a2a', img:'/images/dragons/balerion.jpg', description:'The mightiest dragon ever to have lived. His shadow could swallow entire towns. He forged the Iron Throne with his breath and was the last dragon to have seen Valyria.' },
  { id:'meraxes',   name:'Meraxes',   rider:'Rhaenys Targaryen',      size:'Larger than Vhagar at the time',          fire:'Unknown',                status:'dead',   accent:'#c9a84c', img:'/images/dragons/meraxes.jpg', description:'One of the three conquest dragons. Killed in Dorne — a scorpion bolt through the eye brought both dragon and rider crashing to earth.' },
  { id:'vhagar',    name:'Vhagar',    rider:'Visenya / Aemond / Laena',size:'Largest during the Dance of the Dragons', fire:'Green-bronze flames',    status:'dead',   accent:'#4a6a50', img:'/images/dragons/vhagar.jpg', description:'One of the original three conquest dragons. By the time of the Dance, she was the largest living dragon — ancient, terrifying, and nearly unstoppable.' },
  { id:'caraxes',   name:'Caraxes',   rider:'Daemon Targaryen',       size:'Large, lean, serpentine',                 fire:'Blood-red flames',       status:'dead',   accent:'#8b1a1a', img:'/images/dragons/caraxes.jpg', description:'The Blood Wyrm. A lean, red, fearsome beast ridden by Prince Daemon Targaryen. Perished alongside Vhagar in the legendary Battle Above the Gods Eye.' },
  { id:'syrax',     name:'Syrax',     rider:'Rhaenyra Targaryen',     size:'Large and formidable',                    fire:'Yellow flames',          status:'dead',   accent:'#d4a84b', img:'/images/dragons/syrax.jpg', description:'A yellow-scaled she-dragon ridden by Queen Rhaenyra Targaryen. Though formidable, she had not hunted for years and grew somewhat lazy in the Dragonpit.' },
  { id:'sunfyre',   name:'Sunfyre',   rider:'Aegon II Targaryen',     size:'Young but fierce',                        fire:'Golden flames',          status:'dead',   accent:'#e5c276', img:'/images/dragons/sunfyre.jpg', description:'Known as Sunfyre the Golden. Said to be the most beautiful dragon in the world, with gleaming gold scales and pink wing membranes.' },
  { id:'meleys',    name:'Meleys',    rider:'Rhaenys Targaryen',      size:'Huge and fast',                           fire:'Crimson flames',         status:'dead',   accent:'#b02a2a', img:'/images/dragons/meleys.jpg', description:'The Red Queen. A fearsome dragon with crimson scales and copper highlights. One of the swiftest and most experienced dragons of her era.' },
  { id:'seasmoke',  name:'Seasmoke',  rider:'Laenor Velaryon / Addam',size:'Nimble and maneuverable',                 fire:'Pale flames',            status:'dead',   accent:'#b5bdc4', img:'/images/dragons/seasmoke.jpg', description:'A pale grey-silver dragon. Nimble in the air and instrumental in the War for the Stepstones.' },
  { id:'vermithor', name:'Vermithor', rider:'Jaehaerys I / Hugh',     size:'Second largest after Vhagar',             fire:'Bronze flames',          status:'dead',   accent:'#8b6914', img:'/images/dragons/vermithor.jpg', description:'The Bronze Fury. A massive ancient beast, nearly a hundred years old during the Dance, ridden by the Old King Jaehaerys.' },
];
export const TIMELINE = [
  { era:'The Dawn Age',       year:'~12,000 years ago',  title:'The First Men Arrive',               description:'The First Men crossed the Arm of Dorne, bringing bronze weapons and horses. They warred with the Children of the Forest for centuries before making the Pact on the Isle of Faces.', icon:'🌅' },
  { era:'The Long Night',     year:'~8,000 years ago',   title:'The Long Night',                     description:'A winter that lasted a generation. The White Walkers descended, bringing death and darkness. The Last Hero and the Children forged the first Valyrian steel. The Wall was raised by Bran the Builder.', icon:'❄️' },
  { era:'The Age of Heroes',  year:'~6,000 years ago',   title:'The Wall & The Night\'s Watch',       description:'Bran the Builder raised the Wall — 700 feet of ice stretching 300 miles. The Night\'s Watch was founded to guard the realms of men from the horrors beyond.', icon:'🧱' },
  { era:'Valyrian Freehold',  year:'~5,000 years ago',   title:'The Rise of Valyria',                 description:'In the volcanic peninsula of Valyria, shepherds discovered dragons. They tamed them with sorcery and built the greatest civilization the world had ever known.', icon:'🐉' },
  { era:'The Doom',           year:'~400 years ago',     title:'The Doom of Valyria',                 description:'The Fourteen Flames erupted. The Valyrian Freehold was destroyed in a single night of fire and blood. Only the Targaryens survived, having fled to Dragonstone.', icon:'🌋' },
  { era:"Aegon's Conquest",   year:'1 AC',               title:"Aegon's Conquest",                   description:'Aegon Targaryen and his sister-wives, Visenya and Rhaenys, landed at the mouth of the Blackwater with three dragons. Six kingdoms knelt. Dorne alone resisted.', icon:'👑' },
  { era:"The Great Council",  year:'101 AC',             title:"The Great Council of 101 AC",        description:'King Jaehaerys I convened a massive council at Harrenhal to choose his heir. The lords chose Viserys over Rhaenys, cementing the precedent that a male line takes precedence over a female one.', icon:'📜' },
  { era:"Reign of Viserys I", year:'103–129 AC',         title:"The Reign of Viserys I",             description:'A golden age of peace and prosperity. However, the seeds of war were sown when Viserys named his daughter Rhaenyra as heir, but later fathered a son, Aegon, with his second wife Alicent Hightower.', icon:'🕊️' },
  { era:"The Green Council",  year:'129 AC',             title:"The Green Council",                  description:'Upon the death of King Viserys I, the small council, led by Otto Hightower, conspired in secret to crown Aegon II instead of the chosen heir, Rhaenyra, usurping the Iron Throne.', icon:'🍏' },
  { era:"The Black Council",  year:'129 AC',             title:"The Black Council & Lucerys's Death",description:'Rhaenyra learns of her father\'s death and the usurpation. Her son Lucerys is sent to Storm\'s End as an envoy, but is killed by Aemond Targaryen and Vhagar, marking the true beginning of the war.', icon:'🏴' },
  { era:"Blood and Cheese",   year:'129 AC',             title:"A Son for a Son",                    description:'In retaliation for Lucerys, Prince Daemon orchestrates the infiltration of the Red Keep by assassins known as Blood and Cheese, resulting in the murder of King Aegon II\'s firstborn son.', icon:'🩸' },
  { era:"Rook's Rest",        year:'129 AC',             title:"The Battle at Rook's Rest",          description:'A devastating dragon battle. Princess Rhaenys and Meleys are ambushed by King Aegon II (on Sunfyre) and Prince Aemond (on Vhagar). Rhaenys dies, and Aegon is severely burned and crippled.', icon:'🐉' },
  { era:"The Red Sowing",     year:'129 AC',             title:"The Sowing of the Seeds",            description:'Needing dragonriders, Prince Jacaerys calls upon Targaryen bastards ("dragonseeds") to claim riderless dragons. Hugh Hammer, Ulf White, Addam of Hull, and Nettles succeed in claiming massive beasts.', icon:'🌱' },
  { era:"Fall of King's Landing",year:'130 AC',          title:"The Fall of King's Landing",         description:'Rhaenyra and Daemon take the capital with their dragons while Aemond and Criston Cole are away in the Riverlands. Queen Alicent is taken captive, and Rhaenyra finally sits on the Iron Throne.', icon:'🏛️' },
  { era:"Battle Above the Gods Eye", year:'130 AC',      title:"Battle Above the Gods Eye",          description:'The legendary and fatal duel between Prince Daemon (on Caraxes) and Prince Aemond (on Vhagar) above the waters of the Gods Eye. Daemon leaps from his saddle to drive Dark Sister through Aemond\'s eye as both dragons crash into the lake.', icon:'⚔️' },
  { era:"Storming of the Dragonpit", year:'130 AC',      title:"Storming of the Dragonpit",          description:'Driven to madness by a rioting mob led by the Shepherd, the smallfolk of King\'s Landing storm the Dragonpit. Five dragons are killed in the enclosed space, marking the beginning of the end for the dragons.', icon:'🔥' },
  { era:"Blackfyre Rebellions", year:'196–260 AC',       title:"The Blackfyre Rebellions",           description:'Five rebellions launched by the Blackfyre pretenders against the ruling Targaryens. The wars fractured the realm and gave rise to legendary figures like Bittersteel and Bloodraven.', icon:'🗡️' },
  { era:"Robert's Rebellion", year:'282–283 AC',         title:"Robert's Rebellion",                  description:'The Mad King burned Lord Rickard Stark alive and strangled his heir Brandon. Robert Baratheon, Ned Stark, and Jon Arryn raised their banners in rebellion. The Trident decided the war.', icon:'⚔️' },
  { era:'War of Five Kings',  year:'298–300 AC',         title:'The War of the Five Kings',            description:'After Robert\'s death, five kings claimed power: Joffrey, Stannis, Renly, Robb Stark, and Balon Greyjoy. The realm bled as ambition devoured honor.', icon:'⚔️' },
  { era:'The Red Wedding',    year:'299 AC',             title:'The Red Wedding',                     description:'Under guest right, at the Twins, Walder Frey and Roose Bolton murdered Robb Stark, his mother Catelyn, and his entire army. The North\'s rebellion died in a single night of betrayal.', icon:'🩸' },
  { era:'Battle of Bastards', year:'303 AC',             title:'The Battle of the Bastards',           description:'Jon Snow versus Ramsay Bolton for Winterfell. Thousands died in the crush. The Knights of the Vale turned the tide. The Starks reclaimed their home.', icon:'🐺' },
  { era:'The Long Night Returns', year:'304 AC',         title:'The Great War',                       description:'The Night King breached the Wall with an undead dragon. The living made their stand at Winterfell. Arya Stark ended the threat with a single blade of Valyrian steel.', icon:'🗡️' },
  { era:'The Last War',       year:'305 AC',             title:'The Last War',                        description:'Daenerys burned King\'s Landing. Jon Snow killed the woman he loved. Bran the Broken was chosen as King. The wheel wasn\'t broken — it was remade.', icon:'🏛️' },
]